SERVER_HOST: "0.0.0.0"
SERVER_ORIGINS: "http://localhost:5173"
SERVER_PORT: 5000
DB_AUTOMIGRATE: true
DB_HEADLESS: false
DB_HOST: "server1.oupsn.com"
DB_NAME: "interv-dev"
DB_USERNAME: "interv-dev"
DB_PASSWORD: "interv-dev"
DB_PORT: 5433
sslmode: "disable"
JWT_SECRET: "korHaiProjectNeePanPaiDaiDeeee"
ENV: "dev"
MINIO_ENDPOINT: minio.oupsn.com
MINIO_ACCESS_KEY: interv
MINIO_SECRET_KEY: interv12123
MJ_APIKEY_PUBLIC: "62c6bffbde61fab41d47a4cd3187e2ad"
MJ_APIKEY_PRIVATE: "f40e634957cee3feff39ac6440a250c5"