SERVER_HOST: "0.0.0.0"
SERVER_ORIGINS: "http://localhost:5173"
SERVER_PORT: 5000
DB_AUTOMIGRATE: true
DB_HEADLESS: false
DB_HOST: "server1.oupsn.com"
DB_NAME: "interv-dev"
DB_USERNAME: "interv-dev"
DB_PASSWORD: "interv-dev"
DB_PORT: 5433
JWT_SECRET: "korHaiProjectNeePanPaiDaiDeeee"
ENV: "dev"
MINIO_ENDPOINT: minio.oupsn.com
MINIO_ACCESS_KEY: interv
MINIO_SECRET_KEY: interv12123
COMPILER_ENDPOINT: "http://40.81.16.191:2358/"