basePath: /api
definitions:
  CurrentUser:
    properties:
      created_at:
        type: string
      id:
        type: integer
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    required:
    - created_at
    - id
    - role
    - updated_at
    - username
    type: object
  LoginBody:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  UserCreateBody:
    properties:
      password:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - password
    - role
    - username
    type: object
  UserDeleteBody:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  handlers.ErrResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.OkResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-CurrentUser:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/CurrentUser'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-User:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/User'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-string:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
  title: Interv API
  version: "1.0"
paths:
  /auth.login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: LoginBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Login to the system
      tags:
      - authentication
  /auth.logout:
    post:
      consumes:
      - application/json
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.OkResponse'
      summary: Logout from the system
      tags:
      - authentication
  /auth.me:
    get:
      consumes:
      - application/json
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-CurrentUser'
      summary: Get current user in the system
      tags:
      - authentication
  /user.createUser:
    post:
      consumes:
      - application/json
      operationId: createUser
      parameters:
      - description: CreateUserBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Create new user
      tags:
      - user
  /user.deleteUser:
    post:
      consumes:
      - application/json
      operationId: deleteUser
      parameters:
      - description: DeleteUserBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserDeleteBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete user
      tags:
      - user
swagger: "2.0"
