basePath: /api
definitions:
  AddUserToWorkspaceBody:
    properties:
      status:
        type: string
      user_id:
        type: integer
      workspace_id:
        type: integer
    required:
    - status
    - user_id
    - workspace_id
    type: object
  CreateWorkspaceBody:
    properties:
      iscoding:
        type: boolean
      isvideo:
        type: boolean
      startdate:
        type: string
      stopdate:
        type: string
      title:
        type: string
    required:
    - iscoding
    - isvideo
    - startdate
    - stopdate
    - title
    type: object
  CurrentUserResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    required:
    - created_at
    - id
    - role
    - updated_at
    - username
    type: object
  DeleteUserFromWorkspaceBody:
    properties:
      user_id:
        type: integer
      workspace_id:
        type: integer
    required:
    - user_id
    - workspace_id
    type: object
  DeleteWorkspaceBody:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  GetObjectBody:
    properties:
      bucketName:
        type: string
      objectName:
        type: string
    required:
    - bucketName
    - objectName
    type: object
  GetWorkspaceBody:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  LoginBody:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  UserCreateBody:
    properties:
      password:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - password
    - role
    - username
    type: object
  UserDeleteBody:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  UserInWorkspace:
    properties:
      id:
        type: integer
      isInterest:
        type: boolean
      status:
        type: string
      userId:
        type: integer
      workspaceId:
        type: integer
    type: object
  VideoInterviewContextResponse:
    properties:
      questionSetting:
        items:
          $ref: '#/definitions/VideoInterviewQuestionSetting'
        type: array
      totalQuestions:
        type: integer
    required:
    - questionSetting
    - totalQuestions
    type: object
  VideoInterviewQuestionResponse:
    properties:
      question:
        type: string
      questionIndex:
        type: integer
    required:
    - question
    - questionIndex
    type: object
  VideoInterviewQuestionSetting:
    properties:
      isLast:
        type: boolean
      questionIndex:
        type: integer
      retry:
        type: integer
      timeToAnswer:
        type: integer
      timeToPrepare:
        type: integer
    required:
    - isLast
    - questionIndex
    - retry
    - timeToAnswer
    - timeToPrepare
    type: object
  WorkspaceData:
    properties:
      id:
        type: integer
      iscoding:
        type: boolean
      isvideo:
        type: boolean
      membernum:
        type: integer
      owner:
        type: integer
      startdate:
        type: string
      stopdate:
        type: string
      title:
        type: string
    type: object
  handlers.ErrResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.OkResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-CurrentUserResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/CurrentUserResponse'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-User:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/User'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-UserInWorkspace:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/UserInWorkspace'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-VideoInterviewContextResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/VideoInterviewContextResponse'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-VideoInterviewQuestionResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/VideoInterviewQuestionResponse'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-WorkspaceData:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/WorkspaceData'
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-array_WorkspaceData:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/WorkspaceData'
        type: array
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-string:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
  title: Interv API
  version: "1.0"
paths:
  /auth.login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: LoginBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Login to the system
      tags:
      - authentication
  /auth.logout:
    post:
      consumes:
      - application/json
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.OkResponse'
      summary: Logout from the system
      tags:
      - authentication
  /auth.me:
    get:
      consumes:
      - application/json
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-CurrentUserResponse'
      summary: Get current user in the system
      tags:
      - authentication
  /object.getObject:
    post:
      operationId: getObject
      parameters:
      - description: Get Object Body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/GetObjectBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Get object from the system
      tags:
      - object
  /object.uploadObject:
    post:
      consumes:
      - multipart/form-data
      operationId: uploadObject
      parameters:
      - description: Video Interview File
        in: formData
        name: file
        required: true
        type: file
      - description: Bucket Name
        in: formData
        name: bucketName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Upload object to the system
      tags:
      - object
  /user.createUser:
    post:
      consumes:
      - application/json
      operationId: createUser
      parameters:
      - description: CreateUserBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Create new user
      tags:
      - user
  /user.deleteUser:
    post:
      consumes:
      - application/json
      operationId: deleteUser
      parameters:
      - description: DeleteUserBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserDeleteBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete user
      tags:
      - user
  /userInWorkspace.create:
    post:
      consumes:
      - application/json
      operationId: AddUserToWorkspace
      parameters:
      - description: AddUserToWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/AddUserToWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-UserInWorkspace'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Add User To Workspace
      tags:
      - userInWorkspace
  /userInWorkspace.delete:
    delete:
      consumes:
      - application/json
      operationId: DeleteUserFromWorkspace
      parameters:
      - description: DeleteUserFromWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DeleteUserFromWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-UserInWorkspace'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete User From Workspace
      tags:
      - userInWorkspace
  /videoInterview.getVideoInterviewContext:
    get:
      consumes:
      - application/json
      operationId: getVideoInterviewContext
      parameters:
      - in: query
        name: lobbyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-VideoInterviewContextResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Get video interview context
      tags:
      - videoInterview
  /videoInterview.getVideoInterviewQuestion:
    get:
      consumes:
      - application/json
      operationId: getVideoInterviewQuestion
      parameters:
      - in: query
        name: lobbyId
        required: true
        type: string
      - in: query
        name: questionIndex
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-VideoInterviewQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Get video interview question
      tags:
      - videoInterview
  /videoInterview.submitVideoInterview:
    post:
      consumes:
      - multipart/form-data
      operationId: submitVideoInterview
      parameters:
      - description: Video Interview File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Submit video interview
      tags:
      - videoInterview
  /workspace.create:
    post:
      consumes:
      - application/json
      operationId: CreateWorkspace
      parameters:
      - description: CreateWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-WorkspaceData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Create new workspace
      tags:
      - workspace
  /workspace.delete:
    post:
      consumes:
      - application/json
      operationId: DeleteWorkspace
      parameters:
      - description: DeleteWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DeleteWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete workspace
      tags:
      - workspace
  /workspace.get:
    get:
      consumes:
      - application/json
      operationId: GetWorkspace
      parameters:
      - description: GetWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/GetWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-WorkspaceData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Get workspace
      tags:
      - workspace
  /workspace.getAll:
    get:
      consumes:
      - application/json
      operationId: GetAllWorkspace
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-array_WorkspaceData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Get List of workspace
      tags:
      - workspace
swagger: "2.0"
